sprint 9 tz 1.23
muhammad-di/java-filmorate pull request #29
Opened 2023-07-10 09:19 UTC by muhammad-di

2023-07-10 10:21 UTC, EugeneLenkevich requested changes
Привет, Мухаммад, спасибо за PR

Отличная работа, только пара косметических моментиков :)

2023-07-10 10:21 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Для проверки строк на пустоту можно использовать 
StringUtils.hasText
или же аналогичную функцию из apache commons 
StringUtils.isNotBlank
=)

2023-07-10 10:21 UTC, EugeneLenkevich commented on src/test/java/ru/yandex/practicum/filmorate/validation/UserValidationTest.java
> +        user = User.builder().id(1).email("").login("alexsLogin").name("Alex").birthday(LocalDate.of(2002, 4, 29)).build();
Мне кажется проще не заморачиваться и объявлять каждый раз локальную переменную, чем меньше область видимости переменной - тем лучше, быстрее ее соберет сборщик мусора после того как она станет не нужна :)

ЧИсто стилистический моментик, когда билдер в одну строку сделан трудновато читать бывает, пусть лучше каждый метод в своей строке будет, понятней же и поддерживать проще :)
```
var user  = User.builder()
.id(1)
.email("")
.login("alexsLogin")
.name("Alex")
.birthday(LocalDate.of(2002, 4, 29))
.build();
```

2023-07-10 10:21 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final Map<Integer, Film> films = new HashMap<>();
Вообще, при желании можно использовать ConcurrentHashMap. Web - конкурентная среда :)

https://habr.com/ru/post/132884/

2023-07-10 22:00 UTC, muhammad-di commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final Map<Integer, Film> films = new HashMap<>();
> Вообще, при желании можно использовать ConcurrentHashMap. Web - конкурентная среда :)
> 
> https://habr.com/ru/post/132884/
Здравствуй Евгений! Как всегда спасибо за детальное ревью) Из твоих ссылок на статьи у меня уже набралась целая коллекция))
Ули честно я не все понял из статьи (https://habr.com/ru/post/132884/), но обязательно постараюсь разобрать её более подробно!

2023-07-10 22:03 UTC, muhammad-di commented on src/test/java/ru/yandex/practicum/filmorate/validation/UserValidationTest.java
> +        user = User.builder().id(1).email("").login("alexsLogin").name("Alex").birthday(LocalDate.of(2002, 4, 29)).build();
Это все idea, я не виноват))) случайно нажал два раза на cmd+alt+l и получилось, то что ты видишь))

2023-07-10 22:24 UTC, closed without merging

2023-07-11 04:28 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final Map<Integer, Film> films = new HashMap<>();
Это для общем информации, вообще, многопоточность довольно трудная тема, особенно по статьям если в этом разбираться - вообще ничего не понятно, но, главное, просто знать что вообще такая ситуация есть и существуют специальные коллекциии для работы в многопоточной среде :)