sprint 11 tz 1.0
muhammad-di/java-filmorate pull request #40
Opened 2023-08-22 16:33 UTC by muhammad-di

2023-08-22 17:29 UTC, muhammad-di commented
Привет, Евгений! Как твои дела?
Два теста никак не проходят в git, хотя у меня на локальной машине в postman все нормально) 
Уже все перепробовал и к тому же это тест который показывает что возвращается лист, и лист как раз я вернул)
Надеюсь на твое понимание)

2023-08-22 17:47 UTC, muhammad-di commented
По какой-то причине данные из файла data.sql считываюся дважды

2023-08-22 18:06 UTC, EugeneLenkevich requested changes
Привет, Мухаммад, спасибо за PR

Отметил пару небольших моментов. Что на счет тестов, их требуют зелеными, спроси наставника, он подскажет гораздо быстрее что не так с автотестами, скорее всего где то состояние надо откатывать между тестами, но это мое предположение :)

2023-08-22 21:47 UTC, muhammad-di commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +        if (id < MIN_ID) {
Евгений, я пробовал добавлять @Min(1) анотацию перед (@PathVariable Integer id),
но код все равно пропускает отрицательные числа,
и так же я нашел лишь примеры применения @Min анотации в классах типа модель
Можешь подсказать, как мне применить анотацию в параметрах метода?
И можно ли как-нибудь настроить возвращение ошибки при не совпадении с условиями анотации?

2023-08-23 04:31 UTC, EugeneLenkevich approved these changes
Во, супер, спасибо :)

2023-08-23 06:13 UTC, merged

2023-08-23 06:28 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +        if (id < MIN_ID) {
Где то видел, но что то найти не могу, не помню если честно :)