All new features
muhammad-di/java-filmorate pull request #53
Opened 2023-09-04 05:34 UTC by muhammad-di

2023-09-04 17:35 UTC, EugeneLenkevich requested changes
Привет, Мухаммад! Спасибо за PR.

Отличная работа, спасибо :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2023-09-04 17:35 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        if (!storage.containsDirector(id)) {
!storage.containsDirector(id)

Вот тут мы сначала проверяем на наличие записи а потом ее достаем

storage.getDirectorById(id)

А можно это же сделать за одну операцию: вытащить запись по id, но если она null, то выкинуть исключение, один запрос к БД вместо двух :)

2023-09-04 17:35 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    public Director createDirector(Director director) throws DirectorAlreadyExistException {
Класс называется DirectorService, методы принимают и возвращают объекты Director, наверное из имен можно убрать упоминание имени объекта, может будет покороче без потери выразительности :)

directorService.create(...)
directorService.update(...)
directorService.findById(...)

2023-09-04 17:35 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            return storage.getFilmsWithDirectorIdSortedByLikes(directorId);
storage.getFilmsWithDirectorIdSortedByLikes(directorId)

А что если завести только один метод и передавать в него сортировку. Все таки сортировка - это обязанности хранилища ну и не надо будет под каждую сортировку иметь свой метод :)

2023-09-04 17:35 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationsService.java
> +                    .flatMap(idUser -> filmStorage.getIdLikedFilmsByUser(idUser).stream())
.flatMap(idUser -> filmStorage.getIdLikedFilmsByUser(idUser).stream())

Вот тут в цикле вызывается метод хранилища, то есть каждый раз делается запрос к БД. Запрос к БД - это дорогая операция, это может быть не особо оптимально, а получится достать все необходимые записи за меньшее количество запросов? :)

2023-09-04 17:35 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private void containsUser(Long id) throws UserDoesNotExistException {
Не уверен что для метода выбрано самое выразительное наименования, судя по названию оно проверяет наличие пользователя, однако еще и выкидывает исключение при этом. 
Может вообще вот так делать :)

if(!containsUser(id)) {
  throw new UserDoesNotExistException(...);
}

2023-09-04 17:35 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/dao/impl/ReviewDbStorage.java
> +                "                       WHERE film_id = " + filmId +
" + filmId +

В тексте запросов все же лучше плейсхолдер, то есть параметр использовать, а не конкатенацию строк. Для чисел это еще достаточно безопасно, но вот в случае строк это уязвимость, злоумышленник может указать строку что то типа "; drop users; --" :)

2023-09-04 17:35 UTC, EugeneLenkevich commented on src/main/resources/data.sql
> +--INSERT INTO film (name, release_date, duration, description, mpa) VALUES ('S.F.W.', '2002-10-13', 136, 'Donec dapibus. Duis at velit eu est congue elementum.', 3);
Закомментированный код менее читаем и понятен для других разработчиков, что может привести к ошибкам и проблемам при компиляции или выполнении программы. Поэтому рекомендуется всегда удалять закомментированный код из своего кода программы.

Ну и, скорее всего, все вокруг поменяется и он станет не актуальным, а для истории есть git :)

2023-09-04 17:35 UTC, EugeneLenkevich commented on src/main/resources/schema.sql
> +    content     VARCHAR(250),
250 символов на описание, а не маловато или нормально? :)

2023-09-04 18:13 UTC, muhammad-di commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        if (!storage.containsDirector(id)) {
Я если честно здесь был в метаниях))
Хотел сделать более читабельный код
Но когда ты сказал, что мы теряем в продуктивности, всё стало очевидным))

2023-09-04 18:21 UTC, muhammad-di commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationsService.java
> +                    .flatMap(idUser -> filmStorage.getIdLikedFilmsByUser(idUser).stream())
Мы постараемся реализовать менее ресурсный запрос)

2023-09-04 18:27 UTC, muhammad-di commented on src/main/resources/schema.sql
> +    content     VARCHAR(250),
Я долго не мог решить сколь же символов взять,  посетил сайт imdb и выбрал от туда)
А что если взять 700 символов или это много?

2023-09-04 18:31 UTC, EugeneLenkevich commented on src/main/resources/schema.sql
> +    content     VARCHAR(250),
Я бы вот так сделал, текстовый блоб
content     VARCHAR,

2023-09-04 18:32 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationsService.java
> +                    .flatMap(idUser -> filmStorage.getIdLikedFilmsByUser(idUser).stream())
Самый простой вариант в запросе там где
where id = ...
сделать
where id in (...)

2023-09-04 18:39 UTC, muhammad-di commented on src/main/resources/schema.sql
> +    content     VARCHAR(250),
А как ты думаешь, Евгений, может нам и для описания review тоже связь VARCHAR?

2023-09-04 18:40 UTC, muhammad-di commented on src/main/resources/schema.sql
> +    content     VARCHAR(250),
Спасибо, за ревью, Евгений)
Как всегда полно полезной информации)

2023-09-04 19:03 UTC, EugeneLenkevich commented on src/main/resources/schema.sql
> +    content     VARCHAR(250),
> А как ты думаешь, Евгений, может нам и для описания review тоже связь VARCHAR?

Может быть, насколько понимаю в review может быть большой кусок текста

2023-09-05 06:23 UTC, muhammad-di commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private void containsUser(Long id) throws UserDoesNotExistException {
А что если назвать метод "findEventByUserId" ? Я сперва подумал о названии "findEventById", но боюсь из названия не очевидно кому принадлежит Id, Event или User :)

2023-09-05 06:30 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private void containsUser(Long id) throws UserDoesNotExistException {
Тут уже другое, это разные поля, id и user_id

2023-09-05 18:09 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-09-05 19:19 UTC, merged